import type { NextPage } from 'next'
import Head from 'next/head'
import BodySingle from "components/layouts/body/single/body-single";
import LayoutGeneral from 'components/layouts/layout-general';

interface Props {
    
}

const Index: NextPage<Props> = ({ }) => {

    return (<LayoutGeneral>
            <Head>
                <title>Wowfunding</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BodySingle title={""}>
                <div></div>
            </BodySingle>
            </LayoutGeneral>
    )
}


export default Index
