import type { NextPage } from 'next'
import Head from 'next/head'
import BodySingle from "components/layouts/body/single/body-single";
import LayoutGeneral from 'components/layouts/layout-general';
import ImageCarousel from 'components/layouts/ui/carrousel/carrousel';
import { Grid, Typography } from '@mui/material';
import MediaCard from 'components/layouts/ui/media-card';
import ComoFunciona from 'components/layouts/como-funciona/como-funciona';
import Newsletter from 'components/layouts/newsletter/newsletter';
import FooterAccesos from 'components/layouts/footer-accesos/footer-accesos.component';

interface Props {

}

const Index: NextPage<Props> = ({ }) => {

    return (<LayoutGeneral>
        <Head>
            <title>Wowfunding</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <BodySingle title={""}>
            <div>
                <ImageCarousel />
                <Typography variant='h6' marginBottom={2}>
                    Proyectos recientes
                </Typography>
                <Grid container gap={4}>
                    <MediaCard />
                    <MediaCard />
                    <MediaCard />
                    <MediaCard />
                </Grid>

                <Typography variant='h6' marginBottom={2} marginTop={4}>
                    ¿Cómo funciona wowfunding?
                    <ComoFunciona />
                </Typography>
                <Newsletter />
                <FooterAccesos/>
            </div>
        </BodySingle>
    </LayoutGeneral>
    )
}


export default Index
