server:
  port: ${SERVER_PORT:0}

spring:
  rabbitmq:
    host: 54.90.87.91
    port: 15672
    username: guest
    password: guest
  application:
    name: api-donaciones
  datasource:
    username: ${mysql_username}
    password: ${mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.ctd.academy:3306/${mysql_database}

info:
  application:
    name: api-donaciones

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#cola
queue:
  pi2:
    gp2:
      productos_donaciones: queue.pi2.gp2.productos_donaciones




