server:
  port:  ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: users-api
          uri: lb://USERS-API
          predicates:
            - Path=/auth/**
        - id: api-donaciones
          uri: lb://api-donaciones
          predicates:
            - Path=/api-donaciones/**
          filters:
            - AuthenticationFilter
        - id: mc-productos
          uri: lb://mc-productos
          predicates:
            - Path=/api-productos/**
          filters:
            - AuthenticationFilter


info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://${IP_EUREKA:localhost}:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

