server:
  port:  ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: users-api
          uri: lb://users-api
          predicates:
            - Path=/auth/**
        - id: api-donaciones
          uri: lb://api-donaciones
          predicates:
            - Path=/api-donaciones/**
          filters:
            - AuthenticationFilter
        - id: mc-productos
          uri: lb://mc-productos
          predicates:
            - Path=/api-productos/**
          filters:
            - AuthenticationFilter

# eureka:
#   client:
#     registerWithEureka: true
#     fetchRegistry: true
#     serviceURL:
#       defaultZone: http://${IP_EUREKA:localhost}:8761/eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://${IP_EUREKA:localhost}:8761/eureka
  instance:
    hostName: 44.202.51.198
    ipAddress: 44.202.51.198
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
info:
  app:
    name: ${spring.application.name}
  version: 1.0.0
  date: 2023-12-05

