server:
  port: ${PORT:8761}

spring:
  application:
    name: ms-discovery

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhostt}:${server.port}/eureka/
