server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: users-api
  datasource:
    username: ${mysql_username}
    password: ${mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.ctd.academy:3306/${mysql_database}

info:
  application:
    name: users-api

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://${IP_EUREKA:localhost}:8761/eureka
