spring:
  application:
    name: api-donaciones
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8888}



queue:
  pi2:
    gp2:
      productos_donaciones: queue.pi2.gp2.productos_donaciones