spring:
  application:
    name: mc-productos
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8888}
  jpa:
    hibernate:
      ddl-auto:

queue:
  pi2:
    gp2:
      productos_donaciones: queue.pi2.gp2.productos_donaciones

